### ISSUE TITLE
Плагин для Babel

### ISSUE THREAD

**Issue by AleshaOleg** [samgozman/YoptaScript#11]
Планируется ли YoptaBabel плагин?

**Comment by Dzhakhar** [comment]
Надо бы

**Comment by faergeek** [comment]
Не труЪ название. Надо назвать его "бабий-плагин-йопта"

**Comment by faergeek** [comment]
Интересно, прокатит ли кириллица вообще или придётся свой пакетный менеджер ещё пилить. Предлагайте название xD

**Comment by samgozman** [comment]
Спустя 5 лет это случилось!
...нет, бабель стал вебпаком
