### ISSUE TITLE
чоза void куку в екзамплах нах?

### ISSUE THREAD

**Issue by alexander-shvets** [samgozman/YoptaScript#13]
Ерроры повылазят если [йопта](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/function) задеклареную (на стрелку) вызвать:
```
куку йопта law() {}
law() нах
```
_`> Uncaught ReferenceError: law is not defined(…)`_

Не по понятиям жабаскриптовым на [куку](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/void) стучать конкретно !

**Comment by alexander-shvets** [comment]
а ваще лучше изменить "javascript" на "типоскрипт" (TypeScript), и добавить еще несколько ключевых слов:
понятие -> interface

**Comment by samgozman** [comment]
Исправил в [новом релизе](https://github.com/samgozman/YoptaScript/releases/tag/v0.2.5)
