### ISSUE TITLE
Нет общепринятого выражения "атдуши"

### ISSUE THREAD

**Issue by glebcha** [samgozman/YoptaScript#15]
Можно применять совсместно с "йопта".

**Comment by Enelar** [comment]
break; ?

**Comment by iskus** [comment]
Пацаны, я тоже не чертопетух, в вашу хату разрешите заехать. Раскину чё по чём, не вопрос. Чё могу, без базаров , наваяю!)

**Comment by samgozman** [comment]
@Enelar breack -> харэ

**Comment by nihirash** [comment]
атдуши - это ж return

**Comment by Enelar** [comment]
атдуши это спасибо, надо подумать. Может что то типа close?
Типа `file.write().отдуши`

В css это был бы `!important`.

Может что то с pipe? Типа от души в душу.

Или что то в приеме exception/promise.

```
throw Exception
отдуши пиздец
```
или
```
catch Exception
отдуши неибу
```

**Comment by Deliaz** [comment]
try = побратски (пабрацки | пабратски)

**Comment by Deliaz** [comment]
catch = "аченетак" (аченитак | ачёнетак)

**Comment by samgozman** [comment]
@Deliaz Всё из предложенного добавлено в [новом релизе](https://github.com/samgozman/YoptaScript/archive/v0.3.3.zip)

**Comment by Deliaz** [comment]
@samgozman Круто, спасибо

**Comment by AlexeyTokarev** [comment]
finally - таНеЕбет

**Comment by calmburst** [comment]
finally - наПохуй

**Comment by AlexeyTokarev** [comment]
throw new Error() - пшелНахуй

**Comment by calmburst** [comment]
throw new Error() - этоФиаскоБратан()
