### ISSUE TITLE
Подумать на тему обратного конвертера. 

### ISSUE THREAD

**Issue by shanhaichik** [samgozman/YoptaScript#17]
Предлагаю рассмотреть возможность сделать конвертер из js в "Четко скрипт". 
Область применения:  перегонять исходники и отдавать их не хорошим заказчикам :smile:

**Comment by Tsvetkovv** [comment]
@shanhaichik, [есть же](https://yopta.space/)

**Comment by shanhaichik** [comment]
@Tsvetkovv Спасибо, не заметил с ходу. Значит можно закрывать.

**Comment by samgozman** [comment]
@shanhaichik [Туточки](https://github.com/samgozman/YoptaScript/tree/master/demo/converter) лежат файлики конвертёра. Работает в обе стороны
