### ISSUE TITLE
Сделайте фреймворк для node.js

### ISSUE THREAD

**Issue by batkov** [samgozman/YoptaScript#2]
Без этого йоптаскрипт не полный

**Comment by grushan** [comment]
В будущем все будет. Путь к успеху это дело долгое и ответственное. 
Есть упоминания в йопте о нодах как о говнодах.

**Comment by iamfrontender** [comment]
https://github.com/iamfrontender/your-script

**Comment by freerider7777** [comment]
ждем ноду! очень хотим использовать в серверных решениях! :)

**Comment by samgozman** [comment]
Добавили npm модуль в [новом релизе](https://github.com/samgozman/YoptaScript/archive/v0.3.zip)
Можно юзать на node сервере 💃
