### ISSUE TITLE
Конвертер не обрабатывает классы

### ISSUE THREAD

**Issue by darth-notorious** [samgozman/YoptaScript#34]
Хотя есть для этой цели очевидное слово "масть"

**Comment by samgozman** [comment]
Приведи пример.
Классы в словаре есть:
`, ["Class", "клёво"]
			, ["Class", "клево"]`

**Comment by darth-notorious** [comment]
Так а почему с большой буквы?
`class Point {
    constructor(x, y) {
        this.x = x;
        this.y = y;
    }
    toString() {
        return '(' + this.x + ', ' + this.y + ')';
    }
}
`

**Comment by samgozman** [comment]
@darth-notorious пофиксим

**Comment by samgozman** [comment]
Исправил в [новом релизе](https://github.com/samgozman/YoptaScript/archive/v0.2.7.zip)
