### ISSUE TITLE
Добавьте поддержку буквы е вместо ё

### ISSUE THREAD

**Issue by Livitan** [samgozman/YoptaScript#4]
> `го(i нах i хуёвей 100 нах i сука i + 1) {
    //код
}`

Т.к. буква **ё** используется крайне редко, у реальных пацанов эта кнопка может быть забита скорлупой от  семок или не нажиматься вовсе, как у меня :( 
сделайте что бы `хуёвей ` === `хуевей `

**Comment by samgozman** [comment]
Спасибо!
Добавил в новом релизе: https://github.com/samgozman/YoptaScript/releases/tag/v0.2.3
