### ISSUE TITLE
Перевод с итальянского на русский диалект

### ISSUE THREAD

**Issue by RushOnline** [samgozman/YoptaScript#41]
"трулио" -> "внатуре" или "верняк",например:  ```mnogo = внатуре;```
"нетрулио" -> "пиздёжь", например:  ```пиздишь = tvoi.slova == пиздёжь```
"эквалио" -> "это", например: ```пиздишь = tvoi.slova это пиздёжь```

пул реквест делать лень ёпта, внатуре, но есть ещё много предложений

**Comment by samgozman** [comment]
```
трулио -> чётко -> четко -> true
нетрулио -> пиздишь -> false
эквалио -> ровно -> однахуйня -> ==
```
Чем эти не подошли?) Не слишком ли много диалектов на одни и те же слова?

**Comment by RushOnline** [comment]
> Чем эти не подошли?
чётко - наречие
пиздишь - скорее имя функции

> Не слишком ли много диалектов на одни и те же слова?
Остальное с трудом да, но почему бы и не расширить? Поэму без пул реквеста, на твоё усмотрение.

**Comment by freerider7777** [comment]
внатуре нужно внатуре! :)
язык четкий, респект парни - наконец стоящая отечественная разработка, а не нано-технологии по отмыванию бабла! :)
