### ISSUE TITLE
Не пиздите епта

### ISSUE THREAD

**Issue by Nakilon** [samgozman/YoptaScript#42]
Верстальщики в своем JS-мирке совсем потерялись внатуре.

> первый в мире скриптовый язык программирования для гопников

Язык для четких пацанов был еще пять лет назад https://habrahabr.ru/post/116301/
За базар отвечайте.

**Comment by samgozman** [comment]
Не вырывайте из контекста:

> YoptaScript это первый в мире **скриптовый язык** программирования **для гопников и реальных пацанов**, транслируемый в чистый JavaScript.

С таким же успехом Вы могли бы сказать, что Планкалкюль был первым
