### ISSUE TITLE
Посоны, че за "эквалио"?

### ISSUE THREAD

**Issue by laz2** [samgozman/YoptaScript#49]
`=` - `с*ка`
`!=` - `чобл*с*ка`
значит
`==` - `бл*с*ка`
Епта!
ЗЫ. Ну или `с*кас*ка` на крайняк.

**Comment by alexander-shvets** [comment]
я за = внатуре

**Comment by samgozman** [comment]
@laz2 

> эквалио -> ровно -> однахуйня -> ==

эквалио в нашей учебке называют equal или equalto. Потому один из вариантов написания оставили таковым

**Comment by ua9msn** [comment]
Ну тогда 
== типа 
=== конкретно

**Comment by samgozman** [comment]
@alexander-shvets @ua9msn  Почти всё из предложенного добавлено в [новом релизе](https://github.com/samgozman/YoptaScript/archive/v0.3.1.zip)
