### ISSUE TITLE
не работает демо

### ISSUE THREAD

**Issue by Gaserd** [samgozman/YoptaScript#5]
Очень хотели попользоваться всей семьей, но по каким то причинам, не работает демо.
Причина очень проста, не совсем корректный перевод.
![2016-12-06 17 52 05](https://cloud.githubusercontent.com/assets/5616006/20929926/bcf3e5de-bbdc-11e6-9273-e79d585089d0.png)

**Comment by samgozman** [comment]
Спасибо!
Исправил в новом релизе: https://github.com/samgozman/YoptaScript/releases/tag/v0.2.3
