### ISSUE TITLE
Появились символы ^M (windows newline character) в файле yoptascript.js

### ISSUE THREAD

**Issue by vinterskogen** [samgozman/YoptaScript#52]
После последнего мерджа в Develop (8d16d1d4b952616c027792f30778015c7ad63d3a)  в файле yoptascript.js появилось символы "^M" (windows newline character). В мастере их нет. Похоже на баг редактора или что-подобное.

Diff файла yoptascript.js в этом коммите  - https://github.com/samgozman/YoptaScript/commit/8d16d1d4b952616c027792f30778015c7ad63d3a#diff-95b774c0fe03c6f9d684d0e38447e77a

> 2,771 additions and 2,751 deletions

Судя по количеству удаленных и добавленных строк, обновлена почти каждая строка.

**Comment by samgozman** [comment]
Да, неудачный мёрж :D Забей на этот файл, его вскоре не будет.
В версии 0.3 всё будет разбито по файлам для билда
