### ISSUE TITLE
Math - Гопец?

### ISSUE THREAD

**Issue by Evgeny-** [samgozman/YoptaScript#53]
Предлагаю вариант Ботан/Батан/Очкарик

**Comment by belozerskiy** [comment]
Может лучше тогда Очканавт? :)

**Comment by samgozman** [comment]
Предлагаю ещё кратче - очко
Math.PI...

**Comment by samgozman** [comment]
Всё из предложенного добавлено в [новом релизе](https://github.com/samgozman/YoptaScript/archive/v0.3.1.zip)
