### ISSUE TITLE
Реквест пилить влом

### ISSUE THREAD

**Issue by Warmbellycat** [samgozman/YoptaScript#54]
Предложения по словарю:
Switch естьчо
case аеслинайду
default апохуй
in чоунастут
new захуярить
goto пиздуй
interface еблище/еблет
false нечётко
тождественно равно (===) - чёткоровно
every пошерстим
default из nodejs раздела выкинуть.

Так же имеется бардак, element где-то лох, где-то терпила, нужно быть последовательнее, либо одно, либо другое, document - то ксива, то малява, тоже лучше б определится и выбрать что-то одно.

**Comment by Warmbellycat** [comment]
Запилил https://github.com/samgozman/YoptaScript/pull/55

**Comment by freerider7777** [comment]
кстати неплохо - добавляет целкостности языку

**Comment by samgozman** [comment]
Есть хорошие предложения, часть примем. Только не нужно было пилить пулреквест, тк для многих слов могут быть добавлены дубликаты.

**Comment by Warmbellycat** [comment]
Так я и не настаиваю, просто в ПР явно видно что и где, на словах это описывать несколько сложнее. Ну и на дубликаты бегло проверил, вроде бы не было их.

**Comment by Warmbellycat** [comment]
Ну и форматирование кода, особенно отступы - то табуляции, то пробелы. Пробелы имхо лучше, они у всех будут отображаться одинаково, а табуляции у всех по разному. Есть же PSR (хоть он и не про JS), там рекомендовано 4 пробела на один уровень отступа.

**Comment by samgozman** [comment]
@Warmbellycat у меня в редакторе табуляция на 4 пробела заменяется, потому этого бардака не замечал - возможно пулреквесты + сам где-то накосячил, чего не должно быть

**Comment by Warmbellycat** [comment]
Ни в коем случае не выставляю претензий, у меня тоже замена на 4 пробела, уже привычка в шторме Ctrl+A Ctrl+Alt+L Ctrl+S.

**Comment by samgozman** [comment]
Почти все предложения были добавлены в [новом релизе](https://github.com/samgozman/YoptaScript/archive/v0.3.1.zip). Часть дубликатами, а часть заменили.
