### ISSUE TITLE
Нужно исправить

### ISSUE THREAD

**Issue by alebastrov** [samgozman/YoptaScript#6]
document->малява
write->черкануть

**Comment by alebastrov** [comment]
false->пурга
true->штымп

**Comment by roma-kisel** [comment]
Я бы 'эквалио' заменил на 'зашкварить', 'зашквар' или 'заточка'

**Comment by alex-pobeditel-2004** [comment]
Ну уж тогда скорее "эквалио" -> "однахуйня" :)

**Comment by roma-kisel** [comment]
Ну "однахуйня" норм я вот просто решил к истокам обратиться и найти что-нибудь в словаре. Вот сейчас нашел слово "сходняк" тоже неплохо. Для False ещё нашел классное "Фуфло"

**Comment by MaksimBazarov** [comment]
для False лучше пиздежь

**Comment by grushan** [comment]
Пацаны, трулио это трулио! Трулио - по-пацански, по нашему!

**Comment by yozzh** [comment]
Вношу предложение:
 "==" -> "однахуйня"
 "===" -> "блябуду"

**Comment by schertov** [comment]
Может, вместо трулио/нетрулио можно чёткий(ровный)/мутный, а эквалио заменить на "внатуре"?

**Comment by ev4ern** [comment]
тада уж true на внатуре а false на фуфло. и не гоните пургу

**Comment by alexander-shvets** [comment]
фреймворк (типа Angular) -> зона

**Comment by HackedBeat** [comment]
{ -> кароче
} -> блять

**Comment by samgozman** [comment]
@alex-pobeditel-2004 @yozzh Добавил в [новом релизе](https://github.com/samgozman/YoptaScript/releases/tag/v0.2.5)

**Comment by Enelar** [comment]
@roma-kisel я бы == сделал как 'ровно'

петя() ровно четко
петя() == true

петя() однахуйня пиздишь
петя() == false

**Comment by samgozman** [comment]
@Enelar Добавил псевдонимы для Ваших запросов  в [новом релизе](https://github.com/samgozman/YoptaScript/archive/v0.2.7.zip)
