### ISSUE TITLE
Не работает в Chrome 66.0.3359.181

### ISSUE THREAD

**Issue by JoshuaJakowlew** [samgozman/YoptaScript#73]
Не работает в Chrome 66.0.3359.181
Сделал все по инструкции, в Edge запустилось и успешно работает. В Chrome работает только встроенные в html скрипты. При загрузке скрипта из файла получаю следующее: https://imgur.com/a/6uBsZIt

**Comment by samgozman** [comment]
Нельзя получить из браузера доступ к скриптовонному файлу инициированному другим скриптом, если вы не находитесь в режиме локального сервера. А у нас именно так :D Запусти на хостинге или локальном сервере - 100% заработает
