### ISSUE TITLE
Loader для Webpack

### ISSUE THREAD

**Issue by KristobalJunta** [samgozman/YoptaScript#75]
Сделал для ёпты loader для webpack.
Теперь ёпту можно собирать стильно и современно.

[репа, ёпта](https://github.com/KristobalJunta/yopta-loader)

**Comment by AleshaOleg** [comment]
@KristobalJunta внатуре четко, епта

**Comment by samgozman** [comment]
Добавил webpack в YoptaScript 2.0
Лучше поздно, чем никогда!
Рад приветствовать новые баги!
