### ISSUE TITLE
.

### ISSUE THREAD

**Issue by mazulatas** [samgozman/YoptaScript#76]
![image](https://user-images.githubusercontent.com/6144770/46397672-7b265200-c6fb-11e8-8e07-0bf1ac0f8b81.png)

**Comment by kdelinx** [comment]
Это жыэс, но попытка его усложнить и добавить ещё больше типизации

**Comment by faergeek** [comment]
тупизации скорее. Я за ТипаСкрипт. Кто со мной?

**Comment by kdelinx** [comment]
Могу по вечерам выделять время и контрибьютить в тупоскрипт >^_^<

**Comment by faergeek** [comment]
@kdelinx огонь! 👍 но я пока только после нового года смогу чё то пилить

**Comment by STih07** [comment]
> ![image](https://user-images.githubusercontent.com/6144770/46397672-7b265200-c6fb-11e8-8e07-0bf1ac0f8b81.png)

![image](https://user-images.githubusercontent.com/36886053/75051333-5a1ff600-54d6-11ea-84dc-180ee9db4f85.png)
