### ISSUE TITLE
Ошибка трансляции операторов

### ISSUE THREAD

**Issue by grushan** [samgozman/YoptaScript#8]
Приветствую. 
Неправильно транслируются операторы, ошибка с экранированием, в результате чего строка "гыы кек сука трулио нах" транслируется в "var кек /= true;", от чего невозможно написать ни один проект, собственно.
____
Здарова йбать!
Крч хуйня ебанная с трансляцией йопт. Крч не по понятиям! Я трещу по-нашему: "гыы кек сука трулио нах", а выходит: "var кек /= true". Из-за этого крч я не приду к успеху и не буду пацаном ;(

**Comment by samgozman** [comment]
Спасибо!
Исправил в новом релизе: https://github.com/samgozman/YoptaScript/releases/tag/v0.2.4
