### ISSUE TITLE
НПМ ерр

### ISSUE THREAD

**Issue by Nerwind** [samgozman/YoptaScript#82]
пытался установить сею залупу с помощью нпм, вылезает ошыпка:

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yopta@0.3.5 postinstall: \`gulp build\`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the yopta@0.3.5 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

чего только не пытался делать, всё равно одно и то же
созрел вопрос: **как починить**?
***з.ы.*** остальные пакеты устанавливает нормально, версия нпм последняя, проблема только с йоптаспиртом

**Comment by nagayev** [comment]
@Nerwind  исправление уже в ветке develop-fix

**Comment by samgozman** [comment]
Исправлено в YoptaScript 2.0
Лучше поздно, чем никогда!
Рад приветствовать новые баги!
