### ISSUE TITLE
не устанавливается yopta через npm install yopta

### ISSUE THREAD

**Issue by ToperPlayYT** [samgozman/YoptaScript#84]
Делал все что мог, переустанавливал node устанавливал LTS и обычную. Ничего не помогло.
![image](https://user-images.githubusercontent.com/53517888/118973429-56e61500-b97a-11eb-916b-997716b75e48.png)
![image](https://user-images.githubusercontent.com/53517888/118973468-606f7d00-b97a-11eb-8779-de63531e0598.png)

**Comment by ToperPlayYT** [comment]
Ранее была другая ошибка но после переустановки теперь такая

**Comment by nagayev** [comment]
@ToperPlayYT аналогично
У вас какая версия nodejs?

**Comment by nagayev** [comment]
@ToperPlayYT Работаю над исправлением.
Завтра пришлю PR с исправлением.

**Comment by samgozman** [comment]
> @ToperPlayYT Работаю над проблемой.
> Завтра к вечеру пришлю PR с исправлением.

Постараюсь обновить летом YoptaScript, слишком долго я прятался 🤣

**Comment by nagayev** [comment]
@samgozman прислал PR

**Comment by nagayev** [comment]
@ToperPlayYT исправление уже в ветке develop-fix

**Comment by samgozman** [comment]
Исправлено в YoptaScript 2.0
Лучше поздно, чем никогда!
Рад приветствовать новые баги!
