### ISSUE TITLE
[quistion] Версирование

### ISSUE THREAD

**Issue by nagayev** [samgozman/YoptaScript#94]
Зачем нужна ветка develop, когда есть master?
На мой взгляд для разработки проекта вроде Yoptascript хватит одного master (ну или develop).
Потому что нет гигантского количества кода и/или 100500 контрибуторов.
Так же можно сделать ветки для релизов.
Например stable (последняя стабильная версия) и old-stable (первая версия без тайпскрипта).
Кстати такой подход использует Debian.

**Comment by samgozman** [comment]
Привык так организовывать свои проекты - в master/main рабочее, в dev разработка. Закончил разработку и тестирование - слил в мастер. Как по мне - так удобней.

**Comment by nagayev** [comment]
@samgozman ок
